version: 3.0.8.{build}
image: Visual Studio 2017

configuration:
  - Release
environment:
  PROJECT: toofz.NecroDancer.Leaderboards
  COVERALLS_REPO_TOKEN:
    secure: spJGSvGHMkfuzJo78zMDv7TyXbJsT8ZTGKctut/XGRNdA5wupoIOjsnBmDmhqvMu
  COVERALLS_SERVICE_NAME: appveyor
  COVERALLS_SERVICE_JOB_ID: '%APPVEYOR_JOB_ID%'
cache:
  - packages -> **\packages.config
notifications:
  - provider: Slack
    incoming_webhook:
      secure: c7l1UmXHWpIDLL1awU4r0QYVPToYM/XjV8trFyD1oHArKxs/vBTYiKYScr1EhCUgmEX6sAFBTvkUHF/k5B+cGjzqRBR2XkAO+lzk8cHQ1FI=

before_build:
  - appveyor-retry nuget restore -DisableParallelProcessing
build:
  project: $(PROJECT).sln
  verbosity: minimal

test_script:
  - ps: .\Test-Project.ps1 -Assembly $env:PROJECT
after_test:
  - ps: .\Submit-CodeCoverageResults.ps1

deploy_script:
  - ps: .\Deploy-NuGetPackage.ps1