version: 3.0.2.{build}
image: Visual Studio 2017

configuration:
  - Release
environment:
  PROJECT: toofz.NecroDancer.Leaderboards
cache:
  - packages -> **\packages.config
notifications:
  - provider: Slack
    incoming_webhook:
      secure: c7l1UmXHWpIDLL1awU4r0QYVPToYM/XjV8trFyD1oHArKxs/vBTYiKYScr1EhCUgmEX6sAFBTvkUHF/k5B+cGjzqRBR2XkAO+lzk8cHQ1FI=
nuget:
  disable_publish_on_pr: true

before_build:
  - appveyor-retry nuget restore -DisableParallelProcessing
build:
  project: $(PROJECT).sln
  verbosity: minimal
after_build:
  - nuget pack "%APPVEYOR_BUILD_FOLDER%\%PROJECT%\%PROJECT%.csproj" -Properties "Configuration=%CONFIGURATION%;Platform=AnyCPU" -Symbols

test_script:
  - vstest.console /logger:Appveyor "%PROJECT%.Tests\bin\%CONFIGURATION%\%PROJECT%.Tests.dll"

deploy:
  - provider: NuGet
    symbol_server: https://ci.appveyor.com/nuget/leonard-thieu-h8hvbe0oe9o1/api/v2/package
    api_key:
      secure: NYFwcZ6c2123bMRxjnMflURWFm9/dgsS42R38FGa+8o=
    artifact: /$(PROJECT).*\.nupkg/
    on:
      appveyor_repo_tag: true
